name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.18' ]
    name: Test Go ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: gofmt
      run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
    - name: staticcheck
      uses: reviewdog/action-staticcheck@v1
      with:
        fail_on_error: true
        filter_mode: nofilter
        reporter: github-check
    - name: go vet
      run: go vet ./...
    - name: go test
      run: go test -race -v ./...
    - name: go build
      run: make all
  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint
