name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  go:
    runs-on: ubuntu-latest
    name: Test Go
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: gofmt
      run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
    - name: Run Staticcheck
      uses: dominikh/staticcheck-action@v1
      with:
        install-go: false
        use-cache: true
    - name: go vet
      run: go vet ./...
    - name: go test
      run: go test -race -v ./...
    - name: go build
      run: make all
  node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn lint
